version: '3.9'
services:
  kongx_serve:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kongx_serve
    ports:
      - "8095:8095"

  kong:
    image: kong:2.7
    container_name: kong
    depends_on:
      - kong-db
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"
    networks:
      - kong-net
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_CASSANDRA_CONTACT_POINTS: kong-db
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    command:
      - bash
      - -c
      - |
        sleep 30
        kong migrations bootstrap
        /docker-entrypoint.sh kong docker-start
    
  kong-db:
    image: postgres:9.6
    container_name: kong-db
    ports:
      - "5432:5432"
    networks:
      - kong-net
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      
networks:
  kong-net:
    name: kong-net
    driver: bridge
